sudo: false

language: node_js

node_js:
  - lts/*

cache:
  yarn: true

notification:
  on_success: never
  on_failure: change

script:
  - yarn build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  local_dir: build
  on:
    branch: master


